### ISSUE TITLE
preprocess.py ValueError: Cannot register model architecture for unknown model type (r_transformer_lm)

### ISSUE THREAD

**Issue by archomt** [mattiadg/FBK-Fairseq-ST#2]
When using the preprocess.py, an error pops up saying "ValueError: Cannot register model architecture for unknown model type (r_transformer_lm)".

**Comment by smkim0220** [comment]
> When using the preprocess.py, an error pops up saying "ValueError: Cannot register model architecture for unknown model type (r_transformer_lm)".

I have same problems. Did you solve it?

**Comment by mattiadg** [comment]
It should be solved now.

**Comment by mattiadg** [comment]
Solved with the last commit

**Comment by Letri6102** [comment]
I have same problems. Did you solve it?
